[package]
name = "rulebox-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "rulebox"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
rulebox-rust = { path = "../rulebox-rust" }

[build-dependencies]
pyo3-build-config = "0.22"
